CREATE TABLE users (
  id         INTEGER PRIMARY KEY,
  name VARCHAR(30)
);

CREATE TABLE books (
  id         INTEGER PRIMARY KEY,
  ISN VARCHAR(30),
  autor  VARCHAR(50),
  title VARCHAR (50),
  takedByUser INTEGER
);
ALTER TABLE PUBLIC.BOOKS
  ADD CONSTRAINT BOOKS_USERS__fk
FOREIGN KEY (TAKEDBYUSER) REFERENCES USERS (ID);